name: Auto Deploy
on:
  push:
    branches:
      - tp5
    paths-ignore:
      - README.md
      - LICENSE
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.SERVER_KEY }}
          ARGS: -avz --delete --exclude='*.env' --exclude='runtime/' --exclude='public/images/' --exclude='config/database.php'
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          FOLDER: ./ 
          SERVER_IP: ${{ secrets.SERVER_HOST }} 
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_DESTINATION: /www/wwwroot/apidoc.tp5/
      - name: Execute Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd /www/wwwroot/apidoc.tp5/ 
            composer update